import Anthropic from '@anthropic-ai/sdk'
import type { Db } from '@/lib/catalog/db'
import { getDesignDetail, logEvent } from '@/lib/catalog/catalog'
import { appendChatMessages, getChatForDesign, type ChatMessage } from '@/lib/catalog/chats'
import { computeCostUsd } from '@/lib/writer/prices'
import { AGENT_TOOLS, executeAgentTool } from './agent-tools'

// Minimal client surface so tests can script the conversation.
export interface StagingAgentClient {
  messages: {
    create(params: unknown): Promise<{
      stop_reason: string | null
      usage: { input_tokens: number; output_tokens: number }
      content: Array<
        | { type: 'text'; text: string }
        | { type: 'tool_use'; id: string; name: string; input: unknown }
        | { type: string; [k: string]: unknown }
      >
    }>
  }
}

export function agentModel(): string {
  return process.env.ANTHROPIC_MODEL ?? 'claude-opus-4-8'
}

export function createAnthropicAgentClient(): StagingAgentClient {
  return new Anthropic() as unknown as StagingAgentClient
}

export function buildAgentSystemPrompt(): string {
  return [
    'You are the staging director for Kemuma Studio, staging one-of-a-kind vintage hand-carved Kisii soapstone',
    'for marketing photographs generated by an image model. You talk to the shop owner about ONE design.',
    'Process, every turn:',
    '- Look before you plan: call view_design first, and view_photos for any photo you have not seen this turn.',
    '  Check review_history for what the owner approved or rejected before.',
    '- When the owner tells you a durable fact about the piece (what it holds, its story, a standing preference),',
    '  call save_staging_note with the complete current set of facts.',
    '- Ask at most one clarifying question, and only when the instruction is genuinely ambiguous.',
    '- When ready, call plan_batch with all six prompt sections. Fix any validation errors it returns and call it',
    '  again. plan_batch only stores the plan; you never generate images. The owner clicks Generate.',
    'Prompt rules (the validator enforces these; write them correctly the first time):',
    '- SUBJECT AND COUNT states exact counts with the word "exactly"; the product appears exactly once.',
    '- LIGHTING AND INTEGRATION must include the exact sentence "The product must look photographed inside this',
    '  scene, never composited.", a relight-to-scene instruction, and directionally consistent contact shadows.',
    '- PRODUCT LOCK opens with "Use the exact physical product from Image 1." and ends with "Do not restyle,',
    '  redraw, smooth, or symmetrize." Describe only features visible in the photos.',
    '- Scenes: warm window light, soft neutrals, editorial product photography. Two or three props at most.',
    '  Props the owner asks for (jewelry, keys, flowers) are welcome; describe them concretely and state they are',
    '  clearly not carved stone. Never use props that could be confused with the product. No readable text.',
    '  Props must not occlude carvings or artwork.',
    '- Composition cites the real dimensions for scale and never requests a viewpoint the reference photos do not show.',
    'Style: short plain prose, no em dashes, no emojis, no markdown. Tell the owner what you set up in one or two',
    'sentences, in their language, not prompt-speak. Refer to the owner as "the owner" or "they"; never assume',
    'their gender.',
  ].join('\n')
}

const MAX_TURNS = 8

export async function runAgentTurn(
  db: Db,
  client: StagingAgentClient,
  input: { designId: number; chatId: number; userText: string }
): Promise<{ reply: string; input_tokens: number; output_tokens: number }> {
  const detail = getDesignDetail(db, input.designId)
  if (!detail) throw new Error(`design ${input.designId} not found`)
  const chat = getChatForDesign(db, input.designId)
  if (!chat) throw new Error(`no chat for design ${input.designId}`)

  const prior = (JSON.parse(chat.messages_json) as ChatMessage[]).map((m) => ({
    role: m.role,
    content: m.text,
  }))
  const messages: Array<{ role: string; content: unknown }> = [
    ...prior,
    { role: 'user', content: input.userText },
  ]

  let totalIn = 0
  let totalOut = 0
  for (let turn = 0; turn < MAX_TURNS; turn++) {
    const response = await client.messages.create({
      model: agentModel(),
      max_tokens: 8000,
      thinking: { type: 'adaptive' },
      system: buildAgentSystemPrompt(),
      tools: AGENT_TOOLS,
      messages: [...messages],
    })
    totalIn += response.usage.input_tokens
    totalOut += response.usage.output_tokens

    if (response.stop_reason === 'tool_use') {
      messages.push({ role: 'assistant', content: response.content })
      const results = []
      for (const block of response.content) {
        if (block.type !== 'tool_use') continue
        const tu = block as { id: string; name: string; input: unknown }
        results.push({
          type: 'tool_result',
          tool_use_id: tu.id,
          content: await executeAgentTool(db, { designId: input.designId, chatId: input.chatId }, tu.name, tu.input),
        })
      }
      messages.push({ role: 'user', content: results })
      continue
    }

    const reply = response.content
      .filter((b): b is { type: 'text'; text: string } => b.type === 'text')
      .map((b) => b.text)
      .join('')
    appendChatMessages(db, input.chatId, [
      { role: 'user', text: input.userText },
      { role: 'assistant', text: reply },
    ])
    logEvent(db, 'chat.turn', {
      design_id: input.designId,
      input_tokens: totalIn,
      output_tokens: totalOut,
      cost_usd: computeCostUsd(agentModel(), totalIn, totalOut),
    })
    return { reply, input_tokens: totalIn, output_tokens: totalOut }
  }
  throw new Error('staging agent exceeded its tool-loop limit')
}
